### ISSUE TITLE
Bugfix: Portrait mode warning

### ISSUE THREAD

**Issue by ungerecht** [ungerecht/retro-web-synth#13]
Currently the "Please switch to landscape mode" message is displayed correctly on mobile, but should not be displayed on a desktop/laptop when the window is resized. The purpose of this warning is to prevent the synth from being used in portrait mode since it is meant to be used in a landscape view.

I'm open to any suggestions on different ways to deal with this issue!

**Comment by Senatrius** [comment]
Hi there. I'd like to take a shot at this one. But first, I need a bit more details on how you'd like this done. 

You mentioned that you want to prevent the app being used in portrait mode, but what about phones in landscape mode? Should the warning always appear on phones, regardless of orientation? Because if that's the case, then the error itself would work better if changed to something along the lines of "This app is best viewed in a web browser" or something like that.

So what i'm thinking is, since css can only detect screen size and not what device the app is running on, scrap the css part where `@media` controls landscape and portrait orientation and install `react-device-detect` package. Then it would be possible to render the warning and the `<SynthController />` components conditionally based on the device.

Let me know if there's anything else to clear up or if I got it wrong and I'll take a look at it as soon as I can, if this issue is still open.

**Comment by Senatrius** [comment]
Yes, the stacked controls perhaps wouldn't be too hard to implement, but trying to fit full 3 octaves into portrait mode might make for a poor UX experience. Alright then, I'll take a look at making it work on desktop and mobile landscape. 

One possibility could be to allow for a few less keys (maybe 2 octaves instead of 3) in portrait mode, as a "synth mini" version of sorts and showing full range in landscape. But let's leave that for another time.
